# Generated by Django 3.0.6 on 2020-06-09 00:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookflix', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='editorial',
            options={'verbose_name_plural': 'Editoriales'},
        ),
        migrations.RemoveField(
            model_name='account',
            name='confirmo',
        ),
        migrations.AlterField(
            model_name='billboard',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='autor'),
        ),
        migrations.AlterField(
            model_name='billboard',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='descripcion'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookflix.Author', verbose_name='autor'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genders',
            field=models.ManyToManyField(to='bookflix.Gender', verbose_name='generos'),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='portadas_libros', verbose_name='imagen'),
        ),
        migrations.AlterField(
            model_name='book',
            name='on_normal',
            field=models.BooleanField(default=False, verbose_name='ver en normal'),
        ),
        migrations.AlterField(
            model_name='book',
            name='on_premium',
            field=models.BooleanField(default=False, verbose_name='ver en premium'),
        ),
        migrations.AlterField(
            model_name='bookbychapter',
            name='book',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bookflix.Book', verbose_name='libro'),
        ),
        migrations.AlterField(
            model_name='bookbychapter',
            name='cant_chapter',
            field=models.IntegerField(default=1, verbose_name='Cantidad de capitulos'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookflix.BookByChapter', verbose_name='libro'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookflix.Profile', verbose_name='perfil'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookflix.Book', verbose_name='publicacion'),
        ),
        migrations.AlterField(
            model_name='counterstates',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookflix.Book', verbose_name='publicacion'),
        ),
        migrations.AlterField(
            model_name='creditcards',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
        ),
        migrations.AlterField(
            model_name='expirationdates',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookflix.Book', verbose_name='libro'),
        ),
        migrations.AlterField(
            model_name='expirationdatesbillboard',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookflix.Billboard', verbose_name='publicacion'),
        ),
        migrations.AlterField(
            model_name='like',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookflix.Profile', verbose_name='autor'),
        ),
        migrations.AlterField(
            model_name='like',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookflix.Book', verbose_name='libro'),
        ),
        migrations.AlterField(
            model_name='likecomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookflix.Profile', verbose_name='autor'),
        ),
        migrations.AlterField(
            model_name='likecomment',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookflix.Comment', verbose_name='comentario'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='cuenta'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_of_creation',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha de creacion'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hour_activation',
            field=models.DateTimeField(blank=True, null=True, verbose_name='hora de activacion'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_active_now',
            field=models.BooleanField(default=False, verbose_name='esta activo ahora'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=50, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pleasures_author',
            field=models.ManyToManyField(blank=True, null=True, to='bookflix.Author', verbose_name='autor'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pleasures_editorial',
            field=models.ManyToManyField(blank=True, null=True, to='bookflix.Editorial', verbose_name='editorial'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pleasures_gender',
            field=models.ManyToManyField(blank=True, null=True, to='bookflix.Gender', verbose_name='genero'),
        ),
        migrations.AlterField(
            model_name='stateofbook',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookflix.Book', verbose_name='libro'),
        ),
        migrations.AlterField(
            model_name='stateofbook',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookflix.Profile', verbose_name='perfil'),
        ),
        migrations.AlterField(
            model_name='stateofbook',
            name='state',
            field=models.CharField(choices=[('reading', 'leyendo'), ('future_reading', 'futura lectura'), ('finished', 'terminado')], default='finished', max_length=16, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='updates',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookflix.Book', verbose_name='libro'),
        ),
        migrations.AlterField(
            model_name='updatesbillboard',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookflix.Billboard', verbose_name='publicacion'),
        ),
        migrations.AlterField(
            model_name='usersolicitud',
            name='date_limit_to_attend',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fecha limite'),
        ),
        migrations.AlterField(
            model_name='usersolicitud',
            name='date_of_solicitud',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha de solicitud'),
        ),
        migrations.AlterField(
            model_name='usersolicitud',
            name='type_of_plan',
            field=models.CharField(choices=[('f', 'free'), ('n', 'normal'), ('p', 'premium')], default='f', max_length=2, verbose_name='tipo de plan'),
        ),
        migrations.AlterField(
            model_name='usersolicitud',
            name='type_of_solicitud',
            field=models.CharField(choices=[('1', 'alta'), ('2', 'cambio'), ('4', 'baja')], default='1', max_length=2, verbose_name='tipo de solicitud'),
        ),
        migrations.AlterField(
            model_name='usersolicitud',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
        ),
        migrations.AlterUniqueTogether(
            name='profile',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='Trailer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='titulo')),
                ('description', models.TextField(blank=True, null=True)),
                ('mostrar_en_home', models.BooleanField(default=False)),
                ('video', models.URLField(blank=True, max_length=255, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='autor')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookflix.Book', verbose_name='libro')),
            ],
            options={
                'verbose_name': 'Trailer',
                'verbose_name_plural': 'Trailers',
            },
        ),
    ]
