# Generated by Django 3.0.6 on 2020-06-09 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookflix', '0002_auto_20200608_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='confirmo',
            field=models.BooleanField(default=False),
        ),
    ]
